---
booktitle: Proceedings of KDD-Cup 2009 Competition
publisher: PMLR
logoright: kdd09-150.jpg
supplementalurl: supplemental/JMLRWCP_V7_supplemental.html
volume: 7
year: '2009'
start: 2009-06-28
end: 2009-06-28
published: 2009-12-04
shortname: KDD-Cup 2009
sections:
- name: supplemental
  title: Supplemental
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: DrorKDD2099
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
editor:
- given: Gideon
  family: Dror
- given: Mar
  family: Boullé
- given: Isabelle
  family: Guyon
- given: Vincent
  family: Lemaire
- given: David
  family: Vogel
description: |
  Proceedings of KDD-Cup 2009 Competition
    Held in New York, New York, USA on 28 June 2009

  Published as Volume 7 by the Proceedings of Machine Learning Research on 04 December 2009.

  Volume Edited by:
    Gideon Dror
    Mar Boullé
    Isabelle Guyon
    Vincent Lemaire
    David Vogel

  Series Editors:
    Neil D. Lawrence
date_str: 28 Jun
url: http://proceedings.mlr.press
baseurl: "/v7"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v7
bibtex_copy: true
endnote_copy: true
apa_copy: true
email: ''
conference:
  name: KDD-Cup 2009 Competition
  url: http://www.kdd.org/kdd-cup/view/kdd-cup-2009
  location: New York, New York, USA
  dates:
  - 2009-06-28
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v7.bib
